### ISSUE TITLE
Error connecting to reporting server

### ISSUE THREAD

**Issue by CiGaRReTeM** [lkosson/reportviewercore#18] opened 2021-02-19 11:12 UTC
Hi, 
Firstly thanks a lot for your effort providing this package. 

I´m using the nuget for Winforms (we are migrating an old WinForms solution to .NET 5), but I´m completely stuck when I try to connect to my reporting server calling "RepViewer.ServerReport.GetParameters()". I have amended of course the dll "System.Web.Services", but I receive the next error:

------------------------
   at System.Web.Services.Protocols.SoapClientType..ctor(Type type)
   at System.Web.Services.Protocols.SoapHttpClientProtocol..ctor()
   at Microsoft.Reporting.WinForms.Internal.Soap.ReportingServices2005.Execution.ReportExecutionService..ctor()
   at Microsoft.Reporting.WinForms.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection..ctor(String reportServerLocation, EndpointVersion version)
   at Microsoft.Reporting.WinForms.SoapReportExecutionService.ServerReportSoapProxy..ctor(WindowsIdentity impersonationUser, String reportServerLocation, IEnumerable`1 headers, IEnumerable`1 cookies, EndpointVersion version)
   at Microsoft.Reporting.WinForms.SoapReportExecutionService.get_Service()
   at Microsoft.Reporting.WinForms.SoapReportExecutionService.SetExecutionId(String executionId)
   at Microsoft.Reporting.WinForms.ServerReport.ApplyExecutionIdToService(IReportExecutionService service)
   at Microsoft.Reporting.WinForms.ServerReport.get_Service()
   at Microsoft.Reporting.WinForms.ServerReport.EnsureExecutionSession()
   at Microsoft.Reporting.WinForms.ServerReport.GetParameters()
   at Sims.Win.Controls.frmReportViewer.RefreshReport(ICollection`1 param) 
------------------------

Any ideas? 
Thanks in advance
Daniel Leiva

**Comment by lkosson** [comment] 2021-02-19 12:08
This package is not really intended for use with remote Report Server. Remote processing of ReportViewer depends on pre-WCF SOAP client implementation and uses SoapHttpClientProtocol, which is not supported in .NET Core.

Adding support for remote report processing would require complete rewrite of ReportExecutionService to use ClientBase while maintaining original method signatures. It should be doable, but would require more time than I can invest in this project at the moment.

**Comment by CorsairRO** [comment] 2021-03-04 10:12
Hello,

First of all thank you for the nice work to move this stuff.

Unfortunately all of our report strategy is based on server side rendering.
Therefore the control should be very dummy, just getting the report paginated there.

The problem is that on .NET 5 they removed old legacy crap Web.Services API.
Anyways, .NET 5 knows how to reference old WCF/asmx/SOAP as you can add a connected service like this

Everything that the control does for that, it calls methods from ReportingServiceExcecution2005.asmx

So i had the idea that wherever the control calls an old fashioned web service to use the .NET 5 referenced service to the Execution Service.

I perfectly understand that you dont have the time to do that by yourself. 
As i am very eager to get such functionality, can i please ask you if you still have the original decompiled version with all the breaking references to dlls
I was thinking to add a SoapClient in .NET 5 to the asmx web service. Then replace all the calls he does internally with that one
Because i am not interested at all in loading client side reports, i will strip out those instead of how you did with server side reports

Then i will send the project back after it works, so that we can merge with the current one at a later time

thank you
have a nice day

**Comment by lkosson** [comment] 2021-03-04 10:24
Current version in the repo still contains all the references to an old-style SOAP client. In fact, the stack trace posted in this issue comes directly from .NET Framework code trying to initialize its own configuration and failing due to missing web.config and machine.config files. If you are looking for raw, decompiled sources of original Report Viewer, see initial commit in this repo.

As you pointed out, ReportViewer just calls synchronously methods from `ReportExecution2005.asmx`, which isn't that hard to import to .NET Core project. Troubles start with `RSExecutionConnection` class, extending auto-generated `ReportExecutionService` and overriding several methods.

Anyway, I'm taking a second look into the issue and there is some hope to port it without rewriting too much of existing code.

**Comment by CiGaRReTeM** [comment] 2021-03-04 10:44
Hi both,

@CorsairRO we have migrated a desktop solution to .NET 5 and of course we were using the reportViewer (against server) everywhere (>100 reports). I took a look @lkosson to your code as you indicated and yes you wascompletely right; in fact I started to migrate "ReportExecutionService" in oder to be able to work with .NET 5 new SOAP paradigm... but later I realize that we could replace the control by the reporting service built-in tool in browser... so basically what we did was create a wrapper migrating to .NET 5 (ReportExecution2005.asmx) the methods (LoadReport, RenderReport, GetParameters and SetParameters), use them and replace the reportViewer for a webcontrol calling directly to the render method. 

Just for giving you an idea that it´s possible to replace this control of the hell (Microsoft is not going to migrate this control); it´s a pity; I suppose that they want to give reason to the community to port all into Power BI tools... I´m completely sure that very soon we will see some evolution from @lkosson or another developer who liked to contribute to enable the project to work against server perfectly. 

Thanks
Daniel Leiva

**Comment by CorsairRO** [comment] 2021-03-04 12:18
Hi @CiGaRReTeM 

Can you please be so nice and tell me how is it working for you to Prompt for user parameters and stuff?
And how are you calling methods from the webservice in the browser there

thank you very much

**Comment by lkosson** [comment] 2021-03-04 14:17
I have just committed changes to make server-side reporting work. Compile it from sources and see if it works with your projects. I don't have any of my own, so I could only test it on a sample application - included in this repo.

If you encounter any errors, before reporting please check if you can reproduce them by plugging your report into provided sample application.

**Comment by CorsairRO** [comment] 2021-03-04 15:23
Hello again...

WOW WOW WOW - It works like a charm 🥇 

I tested 2 reports in your recommended test project , one without any parameter and one which i am setting the param.
Both works OK.

Thank you very much for your effort in there...

**Comment by lkosson** [comment] 2021-03-08 05:58
Version 15.1.11 with added server-side reports is now available on NuGet.

**Closed by lkosson** 2021-03-08 05:58 UTC
