### ISSUE TITLE
System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application.

### ISSUE THREAD

**Issue by jkrebsbach** [lkosson/reportviewercore#36] opened 2021-04-14 13:17 UTC
BinaryFormatter is obsolete in AspNet Core in .net5.0

Default .net 5.0 environment - 

System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information. at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream) at System.Resources.Extensions.DeserializingResourceReader.ReadBinaryFormattedObject() at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex) at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode) at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode) at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode) at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString) at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase) at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream) at System.Resources.ResourceManager.GetObject(String name) at Microsoft.ReportingServices.Rendering.ImageRenderer.Renderer..cctor() --- End of inner exception stack trace

--- at Microsoft.ReportingServices.Rendering.ImageRenderer.Renderer..ctor(Boolean physicalPagination) at Microsoft.ReportingServices.Rendering.ImageRenderer.PDFRenderer.Render(Report report, NameValueCollection deviceInfo, Hashtable renderProperties, CreateAndRegisterStream createAndRegisterStream) at Microsoft.ReportingServices.Rendering.ImageRenderer.RendererBase.Render(Report report, NameValueCollection reportServerParameters, NameValueCollection deviceInfo, NameValueCollection clientCapabilities, Hashtable& renderProperties, CreateAndRegisterStream createAndRegisterStream) --- End of inner exception stack trace --- at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings) at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)

Curious if others are also facing this issue?

var report = new LocalReport();
report.ReportPath = $"Resources/{reportName}.rdl"; 
return report.Render(format, deviceInfo); // report.Render throws above exception

**Comment by lkosson** [comment] 2021-04-15 04:56
`BinaryFormatter` is indeed disabled by default in AspNetCore 5.0. As a workaround, please add `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` to your csproj while I explore whether it is possible to replace ResX binary formatted resources with something else.

**Comment by lkosson** [comment] 2021-04-15 05:28
I have decided to remove those resources altogether. No need for `EnableUnsafeBinaryFormatterSerialization` workaround - updated NuGet package coming in a minute.

**Comment by g136660** [comment] 2021-04-16 12:41
Hi, PDF working in last release on Linux?

**Comment by lkosson** [comment] 2021-04-16 15:29
Hello. No, on Linux only available exporters are HTML4.0, HTML5, EXCELOPENXML and WORDOPENXML.

**Comment by tarockx** [comment] 2022-10-12 14:50
Was this problem actually fixed? I see this issue is closed, but I'm experiencing this with the latest version (15.1.17).

Fortunately the workaround works so it's not really a problem, but I'm confused on whether I'm missing something since the issue is marked as closed...

**Comment by jkrebsbach** [comment] 2022-10-12 18:17
I can confirm the fix is working - and am currently running 15.1.16 on .net 6.
But I do not instantiate a ReportViewer, but a LocalReport object from the Microsoft.Reporting.NETCore namespace...

**Comment by lkosson** [comment] 2022-10-13 05:22
@tarockx Can you reproduce the behavior using `ReportViewerCore.Sample.WinForms` project from this repo? When I switched it to .NET 6, the component initializes correctly without the workaround.

**Comment by tarockx** [comment] 2022-11-02 13:55
> @tarockx Can you reproduce the behavior using `ReportViewerCore.Sample.WinForms` project from this repo? When I switched it to .NET 6, the component initializes correctly without the workaround.

Sorry for the late reply. 
I can confirm that @jkrebsbach is correct, if I don't use the `ReportViewer` but use `LocalReport` instead I don't have the issue, so I removed the WinForms assembly entirely and only use the LocalReport instead. Thanks for your support.

**Comment by schtritoff** [comment] 2023-12-08 22:12
> @tarockx Can you reproduce the behavior using `ReportViewerCore.Sample.WinForms` project from this repo? When I switched it to .NET 6, the component initializes correctly without the workaround.

Hi @lkosson! In my app when targeting net8.0-windows (.NET 8) it throws BunaryFormatter exception on instantiation (in constructor) - new Microsoft.Reporting.WinForms.ReportViewer(). None of the workarrounds work. When I switch back to net7.0-windows ReportViewer works fine. Do you know what could be the cause? Compile time is OK but instantiation fails ...

**Comment by lkosson** [comment] 2023-12-09 05:34
Indeed in `RSParams` control (and some other in `WinForms` project) there are some indirect references to `BinaryFormatter` which I have missed.

**Closed** 2023-12-09 12:59 UTC
